// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/maps.proto

package maps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED      ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = 1
	ErrorCode_ERROR_CODE_NOT_FOUND        ErrorCode = 2
	ErrorCode_ERROR_CODE_ALREADY_EXISTS   ErrorCode = 3
	ErrorCode_ERROR_CODE_UNAVAILABLE      ErrorCode = 4
	ErrorCode_ERROR_CODE_INTERNAL         ErrorCode = 5
	ErrorCode_ERROR_CODE_UNAUTHORIZED     ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_ARGUMENT",
		2: "ERROR_CODE_NOT_FOUND",
		3: "ERROR_CODE_ALREADY_EXISTS",
		4: "ERROR_CODE_UNAVAILABLE",
		5: "ERROR_CODE_INTERNAL",
		6: "ERROR_CODE_UNAUTHORIZED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":      0,
		"ERROR_CODE_INVALID_ARGUMENT": 1,
		"ERROR_CODE_NOT_FOUND":        2,
		"ERROR_CODE_ALREADY_EXISTS":   3,
		"ERROR_CODE_UNAVAILABLE":      4,
		"ERROR_CODE_INTERNAL":         5,
		"ERROR_CODE_UNAUTHORIZED":     6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_maps_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_maps_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=maps.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_maps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GatewayPutRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Region             string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	GatewayIp          string                 `protobuf:"bytes,2,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayPort        int32                  `protobuf:"varint,4,opt,name=gateway_port,json=gatewayPort,proto3" json:"gateway_port,omitempty"`
	Capacity           *Capacity              `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,6,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GatewayPutRequest) Reset() {
	*x = GatewayPutRequest{}
	mi := &file_proto_maps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPutRequest) ProtoMessage() {}

func (x *GatewayPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPutRequest.ProtoReflect.Descriptor instead.
func (*GatewayPutRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayPutRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayPort() int32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *GatewayPutRequest) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *GatewayPutRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

type Capacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int32                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int32                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int32                  `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Bandwidth     int32                  `protobuf:"varint,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_proto_maps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{2}
}

func (x *Capacity) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Capacity) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Capacity) GetStorage() int32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *Capacity) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

type GatewayResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayId      string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	GatewayIp      string                 `protobuf:"bytes,2,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayAddress string                 `protobuf:"bytes,3,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	Error          *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayResponse) Reset() {
	*x = GatewayResponse{}
	mi := &file_proto_maps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayResponse) ProtoMessage() {}

func (x *GatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayResponse.ProtoReflect.Descriptor instead.
func (*GatewayResponse) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayResponse) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayResponse) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *GatewayResponse) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

func (x *GatewayResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type AgentConnectionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentDomain        string                 `protobuf:"bytes,1,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,2,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	Region             string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentConnectionRequest) Reset() {
	*x = AgentConnectionRequest{}
	mi := &file_proto_maps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConnectionRequest) ProtoMessage() {}

func (x *AgentConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConnectionRequest.ProtoReflect.Descriptor instead.
func (*AgentConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{4}
}

func (x *AgentConnectionRequest) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *AgentConnectionRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

func (x *AgentConnectionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type AgentConnect struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayIp      string                 `protobuf:"bytes,1,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayId      string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Region         string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	AgentDomain    string                 `protobuf:"bytes,4,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	GatewayAddress string                 `protobuf:"bytes,5,opt,name=GatewayAddress,proto3" json:"GatewayAddress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentConnect) Reset() {
	*x = AgentConnect{}
	mi := &file_proto_maps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConnect) ProtoMessage() {}

func (x *AgentConnect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConnect.ProtoReflect.Descriptor instead.
func (*AgentConnect) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{5}
}

func (x *AgentConnect) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *AgentConnect) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AgentConnect) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentConnect) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *AgentConnect) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

type AgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentDomain   string                 `protobuf:"bytes,2,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	GatewayId     string                 `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Capacity      *Capacity              `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Error         *Error                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_proto_maps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{6}
}

func (x *AgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentResponse) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *AgentResponse) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AgentResponse) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *AgentResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GatewayHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayHandshake) Reset() {
	*x = GatewayHandshake{}
	mi := &file_proto_maps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHandshake) ProtoMessage() {}

func (x *GatewayHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHandshake.ProtoReflect.Descriptor instead.
func (*GatewayHandshake) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayHandshake) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type MultipleGateways struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*GatewayResponse     `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleGateways) Reset() {
	*x = MultipleGateways{}
	mi := &file_proto_maps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleGateways) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleGateways) ProtoMessage() {}

func (x *MultipleGateways) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleGateways.ProtoReflect.Descriptor instead.
func (*MultipleGateways) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{8}
}

func (x *MultipleGateways) GetGateways() []*GatewayResponse {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *MultipleGateways) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GatewayProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentDomain   string                 `protobuf:"bytes,1,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	ProxyId       string                 `protobuf:"bytes,3,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayProxy) Reset() {
	*x = GatewayProxy{}
	mi := &file_proto_maps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayProxy) ProtoMessage() {}

func (x *GatewayProxy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayProxy.ProtoReflect.Descriptor instead.
func (*GatewayProxy) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayProxy) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *GatewayProxy) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GatewayProxy) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

type ProxyConnectionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Region             string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,3,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProxyConnectionRequest) Reset() {
	*x = ProxyConnectionRequest{}
	mi := &file_proto_maps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConnectionRequest) ProtoMessage() {}

func (x *ProxyConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConnectionRequest.ProtoReflect.Descriptor instead.
func (*ProxyConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{10}
}

func (x *ProxyConnectionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProxyConnectionRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

var File_proto_maps_proto protoreflect.FileDescriptor

const file_proto_maps_proto_rawDesc = "" +
	"\n" +
	"\x10proto/maps.proto\x12\x04maps\"F\n" +
	"\x05Error\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.maps.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcb\x01\n" +
	"\x11GatewayPutRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x02 \x01(\tR\tgatewayIp\x12!\n" +
	"\fgateway_port\x18\x04 \x01(\x05R\vgatewayPort\x12*\n" +
	"\bcapacity\x18\x05 \x01(\v2\x0e.maps.CapacityR\bcapacity\x120\n" +
	"\x14verifiable_cred_hash\x18\x06 \x01(\tR\x12verifiableCredHash\"l\n" +
	"\bCapacity\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x05R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x05R\x06memory\x12\x18\n" +
	"\astorage\x18\x03 \x01(\x05R\astorage\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\x05R\tbandwidth\"\x9b\x01\n" +
	"\x0fGatewayResponse\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x02 \x01(\tR\tgatewayIp\x12'\n" +
	"\x0fgateway_address\x18\x03 \x01(\tR\x0egatewayAddress\x12!\n" +
	"\x05error\x18\x04 \x01(\v2\v.maps.ErrorR\x05error\"\x85\x01\n" +
	"\x16AgentConnectionRequest\x12!\n" +
	"\fagent_domain\x18\x01 \x01(\tR\vagentDomain\x120\n" +
	"\x14verifiable_cred_hash\x18\x02 \x01(\tR\x12verifiableCredHash\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\xaf\x01\n" +
	"\fAgentConnect\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x01 \x01(\tR\tgatewayIp\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12!\n" +
	"\fagent_domain\x18\x04 \x01(\tR\vagentDomain\x12&\n" +
	"\x0eGatewayAddress\x18\x05 \x01(\tR\x0eGatewayAddress\"\xbb\x01\n" +
	"\rAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fagent_domain\x18\x02 \x01(\tR\vagentDomain\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayId\x12*\n" +
	"\bcapacity\x18\x04 \x01(\v2\x0e.maps.CapacityR\bcapacity\x12!\n" +
	"\x05error\x18\x05 \x01(\v2\v.maps.ErrorR\x05error\"*\n" +
	"\x10GatewayHandshake\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"h\n" +
	"\x10MultipleGateways\x121\n" +
	"\bgateways\x18\x01 \x03(\v2\x15.maps.GatewayResponseR\bgateways\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.maps.ErrorR\x05error\"d\n" +
	"\fGatewayProxy\x12!\n" +
	"\fagent_domain\x18\x01 \x01(\tR\vagentDomain\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x19\n" +
	"\bproxy_id\x18\x03 \x01(\tR\aproxyId\"b\n" +
	"\x16ProxyConnectionRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x120\n" +
	"\x14verifiable_cred_hash\x18\x03 \x01(\tR\x12verifiableCredHash*\xd3\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x03\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x04\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x05\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x062\xde\x02\n" +
	"\x04Maps\x12A\n" +
	"\x0fRegisterGateway\x12\x17.maps.GatewayPutRequest\x1a\x15.maps.GatewayResponse\x12B\n" +
	"\rRegisterAgent\x12\x1c.maps.AgentConnectionRequest\x1a\x13.maps.AgentResponse\x12H\n" +
	"\x16ResolveGatewayForAgent\x12\x16.maps.GatewayHandshake\x1a\x16.maps.MultipleGateways\x12C\n" +
	"\x16ResolveGatewayForProxy\x12\x12.maps.GatewayProxy\x1a\x15.maps.GatewayResponse\x12@\n" +
	"\x15ConnectAgentTogateway\x12\x12.maps.AgentConnect\x1a\x13.maps.AgentResponseB6Z4github.com/Purple-House/memstore/registry/proto;mapsb\x06proto3"

var (
	file_proto_maps_proto_rawDescOnce sync.Once
	file_proto_maps_proto_rawDescData []byte
)

func file_proto_maps_proto_rawDescGZIP() []byte {
	file_proto_maps_proto_rawDescOnce.Do(func() {
		file_proto_maps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maps_proto_rawDesc), len(file_proto_maps_proto_rawDesc)))
	})
	return file_proto_maps_proto_rawDescData
}

var file_proto_maps_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_maps_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_maps_proto_goTypes = []any{
	(ErrorCode)(0),                 // 0: maps.ErrorCode
	(*Error)(nil),                  // 1: maps.Error
	(*GatewayPutRequest)(nil),      // 2: maps.GatewayPutRequest
	(*Capacity)(nil),               // 3: maps.Capacity
	(*GatewayResponse)(nil),        // 4: maps.GatewayResponse
	(*AgentConnectionRequest)(nil), // 5: maps.AgentConnectionRequest
	(*AgentConnect)(nil),           // 6: maps.AgentConnect
	(*AgentResponse)(nil),          // 7: maps.AgentResponse
	(*GatewayHandshake)(nil),       // 8: maps.GatewayHandshake
	(*MultipleGateways)(nil),       // 9: maps.MultipleGateways
	(*GatewayProxy)(nil),           // 10: maps.GatewayProxy
	(*ProxyConnectionRequest)(nil), // 11: maps.ProxyConnectionRequest
}
var file_proto_maps_proto_depIdxs = []int32{
	0,  // 0: maps.Error.code:type_name -> maps.ErrorCode
	3,  // 1: maps.GatewayPutRequest.capacity:type_name -> maps.Capacity
	1,  // 2: maps.GatewayResponse.error:type_name -> maps.Error
	3,  // 3: maps.AgentResponse.capacity:type_name -> maps.Capacity
	1,  // 4: maps.AgentResponse.error:type_name -> maps.Error
	4,  // 5: maps.MultipleGateways.gateways:type_name -> maps.GatewayResponse
	1,  // 6: maps.MultipleGateways.error:type_name -> maps.Error
	2,  // 7: maps.Maps.RegisterGateway:input_type -> maps.GatewayPutRequest
	5,  // 8: maps.Maps.RegisterAgent:input_type -> maps.AgentConnectionRequest
	8,  // 9: maps.Maps.ResolveGatewayForAgent:input_type -> maps.GatewayHandshake
	10, // 10: maps.Maps.ResolveGatewayForProxy:input_type -> maps.GatewayProxy
	6,  // 11: maps.Maps.ConnectAgentTogateway:input_type -> maps.AgentConnect
	4,  // 12: maps.Maps.RegisterGateway:output_type -> maps.GatewayResponse
	7,  // 13: maps.Maps.RegisterAgent:output_type -> maps.AgentResponse
	9,  // 14: maps.Maps.ResolveGatewayForAgent:output_type -> maps.MultipleGateways
	4,  // 15: maps.Maps.ResolveGatewayForProxy:output_type -> maps.GatewayResponse
	7,  // 16: maps.Maps.ConnectAgentTogateway:output_type -> maps.AgentResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_maps_proto_init() }
func file_proto_maps_proto_init() {
	if File_proto_maps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maps_proto_rawDesc), len(file_proto_maps_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_maps_proto_goTypes,
		DependencyIndexes: file_proto_maps_proto_depIdxs,
		EnumInfos:         file_proto_maps_proto_enumTypes,
		MessageInfos:      file_proto_maps_proto_msgTypes,
	}.Build()
	File_proto_maps_proto = out.File
	file_proto_maps_proto_goTypes = nil
	file_proto_maps_proto_depIdxs = nil
}
