// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.2
// source: proto/wal.proto

package wal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OP_UNKNOWN     Operation = 0
	Operation_OP_PUT_GATEWAY Operation = 1
	Operation_OP_PUT_AGENT   Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OP_UNKNOWN",
		1: "OP_PUT_GATEWAY",
		2: "OP_PUT_AGENT",
	}
	Operation_value = map[string]int32{
		"OP_UNKNOWN":     0,
		"OP_PUT_GATEWAY": 1,
		"OP_PUT_AGENT":   2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wal_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_wal_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{0}
}

type WalRecord struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Op            Operation               `protobuf:"varint,1,opt,name=op,proto3,enum=wal.Operation" json:"op,omitempty"`
	Gateway       *GatewayPutRequest      `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"` // optional
	Agent         *AgentConnectionRequest `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`     // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalRecord) Reset() {
	*x = WalRecord{}
	mi := &file_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalRecord) ProtoMessage() {}

func (x *WalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalRecord.ProtoReflect.Descriptor instead.
func (*WalRecord) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WalRecord) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_OP_UNKNOWN
}

func (x *WalRecord) GetGateway() *GatewayPutRequest {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *WalRecord) GetAgent() *AgentConnectionRequest {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GatewayPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	GatewayIp     string                 `protobuf:"bytes,2,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayDomain string                 `protobuf:"bytes,3,opt,name=gateway_domain,json=gatewayDomain,proto3" json:"gateway_domain,omitempty"`
	GatewayPort   int32                  `protobuf:"varint,4,opt,name=gateway_port,json=gatewayPort,proto3" json:"gateway_port,omitempty"`
	Capacity      *Capacity              `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayPutRequest) Reset() {
	*x = GatewayPutRequest{}
	mi := &file_proto_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPutRequest) ProtoMessage() {}

func (x *GatewayPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPutRequest.ProtoReflect.Descriptor instead.
func (*GatewayPutRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayPutRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayDomain() string {
	if x != nil {
		return x.GatewayDomain
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayPort() int32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *GatewayPutRequest) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type AgentConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	GatewayId     string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	AgentDomain   string                 `protobuf:"bytes,4,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConnectionRequest) Reset() {
	*x = AgentConnectionRequest{}
	mi := &file_proto_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConnectionRequest) ProtoMessage() {}

func (x *AgentConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConnectionRequest.ProtoReflect.Descriptor instead.
func (*AgentConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConnectionRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AgentConnectionRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AgentConnectionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentConnectionRequest) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

type Capacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int32                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int32                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int32                  `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Bandwidth     int32                  `protobuf:"varint,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_proto_wal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{3}
}

func (x *Capacity) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Capacity) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Capacity) GetStorage() int32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *Capacity) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

var File_proto_wal_proto protoreflect.FileDescriptor

var file_proto_wal_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x77, 0x61, 0x6c, 0x22, 0x90, 0x01, 0x0a, 0x09, 0x57, 0x61, 0x6c, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x02, 0x6f, 0x70, 0x12, 0x30, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x31, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xbf, 0x01, 0x0a, 0x11, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x49, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x21, 0x0a,
	0x0c, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x29, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x22, 0x8a, 0x01, 0x0a, 0x16,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x6c, 0x0a, 0x08, 0x43, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x64,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x61, 0x6e,
	0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x2a, 0x41, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x50, 0x5f, 0x50, 0x55, 0x54, 0x5f, 0x47, 0x41,
	0x54, 0x45, 0x57, 0x41, 0x59, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x50, 0x5f, 0x50, 0x55,
	0x54, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x75, 0x72, 0x70, 0x6c, 0x65, 0x2d, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x6d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x77, 0x61, 0x6c, 0x3b, 0x77, 0x61, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_wal_proto_rawDescOnce sync.Once
	file_proto_wal_proto_rawDescData []byte
)

func file_proto_wal_proto_rawDescGZIP() []byte {
	file_proto_wal_proto_rawDescOnce.Do(func() {
		file_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)))
	})
	return file_proto_wal_proto_rawDescData
}

var file_proto_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_wal_proto_goTypes = []any{
	(Operation)(0),                 // 0: wal.Operation
	(*WalRecord)(nil),              // 1: wal.WalRecord
	(*GatewayPutRequest)(nil),      // 2: wal.GatewayPutRequest
	(*AgentConnectionRequest)(nil), // 3: wal.AgentConnectionRequest
	(*Capacity)(nil),               // 4: wal.Capacity
}
var file_proto_wal_proto_depIdxs = []int32{
	0, // 0: wal.WalRecord.op:type_name -> wal.Operation
	2, // 1: wal.WalRecord.gateway:type_name -> wal.GatewayPutRequest
	3, // 2: wal.WalRecord.agent:type_name -> wal.AgentConnectionRequest
	4, // 3: wal.GatewayPutRequest.capacity:type_name -> wal.Capacity
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_wal_proto_init() }
func file_proto_wal_proto_init() {
	if File_proto_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wal_proto_goTypes,
		DependencyIndexes: file_proto_wal_proto_depIdxs,
		EnumInfos:         file_proto_wal_proto_enumTypes,
		MessageInfos:      file_proto_wal_proto_msgTypes,
	}.Build()
	File_proto_wal_proto = out.File
	file_proto_wal_proto_goTypes = nil
	file_proto_wal_proto_depIdxs = nil
}
