// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wal/proto/wal.proto

package wal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OP_UNKNOWN     Operation = 0
	Operation_OP_PUT_GATEWAY Operation = 1
	Operation_OP_PUT_AGENT   Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OP_UNKNOWN",
		1: "OP_PUT_GATEWAY",
		2: "OP_PUT_AGENT",
	}
	Operation_value = map[string]int32{
		"OP_UNKNOWN":     0,
		"OP_PUT_GATEWAY": 1,
		"OP_PUT_AGENT":   2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_wal_proto_wal_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_wal_proto_wal_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{0}
}

type WalRecord struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Op            Operation               `protobuf:"varint,1,opt,name=op,proto3,enum=wal.Operation" json:"op,omitempty"`
	Gateway       *GatewayPutRequest      `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"` // optional
	Agent         *AgentConnectionRequest `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`     // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalRecord) Reset() {
	*x = WalRecord{}
	mi := &file_wal_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalRecord) ProtoMessage() {}

func (x *WalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalRecord.ProtoReflect.Descriptor instead.
func (*WalRecord) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WalRecord) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_OP_UNKNOWN
}

func (x *WalRecord) GetGateway() *GatewayPutRequest {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *WalRecord) GetAgent() *AgentConnectionRequest {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GatewayPutRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Region             string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	GatewayIp          string                 `protobuf:"bytes,2,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayAddress     string                 `protobuf:"bytes,3,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	GatewayPort        int32                  `protobuf:"varint,4,opt,name=gateway_port,json=gatewayPort,proto3" json:"gateway_port,omitempty"`
	Capacity           *Capacity              `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	GatewayId          string                 `protobuf:"bytes,6,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,7,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	WssPort            int32                  `protobuf:"varint,8,opt,name=wss_port,json=wssPort,proto3" json:"wss_port,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GatewayPutRequest) Reset() {
	*x = GatewayPutRequest{}
	mi := &file_wal_proto_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPutRequest) ProtoMessage() {}

func (x *GatewayPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPutRequest.ProtoReflect.Descriptor instead.
func (*GatewayPutRequest) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayPutRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayPort() int32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *GatewayPutRequest) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *GatewayPutRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayPutRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

func (x *GatewayPutRequest) GetWssPort() int32 {
	if x != nil {
		return x.WssPort
	}
	return 0
}

type AgentConnectionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GatewayAddress     string                 `protobuf:"bytes,1,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	GatewayId          string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Region             string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	AgentDomain        string                 `protobuf:"bytes,4,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	AgentId            string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,6,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentConnectionRequest) Reset() {
	*x = AgentConnectionRequest{}
	mi := &file_wal_proto_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConnectionRequest) ProtoMessage() {}

func (x *AgentConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConnectionRequest.ProtoReflect.Descriptor instead.
func (*AgentConnectionRequest) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConnectionRequest) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

func (x *AgentConnectionRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AgentConnectionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentConnectionRequest) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *AgentConnectionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentConnectionRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

type Capacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int32                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int32                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int32                  `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Bandwidth     int32                  `protobuf:"varint,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_wal_proto_wal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{3}
}

func (x *Capacity) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Capacity) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Capacity) GetStorage() int32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *Capacity) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

var File_wal_proto_wal_proto protoreflect.FileDescriptor

const file_wal_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x13wal/proto/wal.proto\x12\x03wal\"\x90\x01\n" +
	"\tWalRecord\x12\x1e\n" +
	"\x02op\x18\x01 \x01(\x0e2\x0e.wal.OperationR\x02op\x120\n" +
	"\agateway\x18\x02 \x01(\v2\x16.wal.GatewayPutRequestR\agateway\x121\n" +
	"\x05agent\x18\x03 \x01(\v2\x1b.wal.AgentConnectionRequestR\x05agent\"\xad\x02\n" +
	"\x11GatewayPutRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x02 \x01(\tR\tgatewayIp\x12'\n" +
	"\x0fgateway_address\x18\x03 \x01(\tR\x0egatewayAddress\x12!\n" +
	"\fgateway_port\x18\x04 \x01(\x05R\vgatewayPort\x12)\n" +
	"\bcapacity\x18\x05 \x01(\v2\r.wal.CapacityR\bcapacity\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x06 \x01(\tR\tgatewayId\x120\n" +
	"\x14verifiable_cred_hash\x18\a \x01(\tR\x12verifiableCredHash\x12\x19\n" +
	"\bwss_port\x18\b \x01(\x05R\awssPort\"\xe8\x01\n" +
	"\x16AgentConnectionRequest\x12'\n" +
	"\x0fgateway_address\x18\x01 \x01(\tR\x0egatewayAddress\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12!\n" +
	"\fagent_domain\x18\x04 \x01(\tR\vagentDomain\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x120\n" +
	"\x14verifiable_cred_hash\x18\x06 \x01(\tR\x12verifiableCredHash\"l\n" +
	"\bCapacity\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x05R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x05R\x06memory\x12\x18\n" +
	"\astorage\x18\x03 \x01(\x05R\astorage\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\x05R\tbandwidth*A\n" +
	"\tOperation\x12\x0e\n" +
	"\n" +
	"OP_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eOP_PUT_GATEWAY\x10\x01\x12\x10\n" +
	"\fOP_PUT_AGENT\x10\x02B9Z7github.com/Purple-House/memstore/registry/wal/proto;walb\x06proto3"

var (
	file_wal_proto_wal_proto_rawDescOnce sync.Once
	file_wal_proto_wal_proto_rawDescData []byte
)

func file_wal_proto_wal_proto_rawDescGZIP() []byte {
	file_wal_proto_wal_proto_rawDescOnce.Do(func() {
		file_wal_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_proto_wal_proto_rawDesc), len(file_wal_proto_wal_proto_rawDesc)))
	})
	return file_wal_proto_wal_proto_rawDescData
}

var file_wal_proto_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wal_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wal_proto_wal_proto_goTypes = []any{
	(Operation)(0),                 // 0: wal.Operation
	(*WalRecord)(nil),              // 1: wal.WalRecord
	(*GatewayPutRequest)(nil),      // 2: wal.GatewayPutRequest
	(*AgentConnectionRequest)(nil), // 3: wal.AgentConnectionRequest
	(*Capacity)(nil),               // 4: wal.Capacity
}
var file_wal_proto_wal_proto_depIdxs = []int32{
	0, // 0: wal.WalRecord.op:type_name -> wal.Operation
	2, // 1: wal.WalRecord.gateway:type_name -> wal.GatewayPutRequest
	3, // 2: wal.WalRecord.agent:type_name -> wal.AgentConnectionRequest
	4, // 3: wal.GatewayPutRequest.capacity:type_name -> wal.Capacity
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wal_proto_wal_proto_init() }
func file_wal_proto_wal_proto_init() {
	if File_wal_proto_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_proto_wal_proto_rawDesc), len(file_wal_proto_wal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_proto_wal_proto_goTypes,
		DependencyIndexes: file_wal_proto_wal_proto_depIdxs,
		EnumInfos:         file_wal_proto_wal_proto_enumTypes,
		MessageInfos:      file_wal_proto_wal_proto_msgTypes,
	}.Build()
	File_wal_proto_wal_proto = out.File
	file_wal_proto_wal_proto_goTypes = nil
	file_wal_proto_wal_proto_depIdxs = nil
}
